CREATE TABLE users (
 id UUID PRIMARY KEY, email VARCHAR(254) NOT NULL UNIQUE, password VARCHAR(255) NOT NULL,
 full_name VARCHAR(100) NOT NULL, phone_number VARCHAR(16) NOT NULL UNIQUE,
 role VARCHAR(32) NOT NULL CHECK (role IN ('USER','SHOPKEEPER','ADMIN')),
 verified BOOLEAN NOT NULL DEFAULT FALSE, version BIGINT NOT NULL DEFAULT 0
);
CREATE TABLE otp_challenges (
 phone VARCHAR(16) PRIMARY KEY, code_hash VARCHAR(255) NOT NULL,
 expires_at TIMESTAMP WITH TIME ZONE NOT NULL, sent_at TIMESTAMP WITH TIME ZONE NOT NULL,
 attempts INTEGER NOT NULL DEFAULT 0, proof_hash VARCHAR(255), proof_expires_at TIMESTAMP WITH TIME ZONE
);
