server:
  port: ${PORT:8082}
spring:
  config:
    import: classpath:backend-defaults.yml
  application:
    name: UserService
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/users}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
sms:
  enabled: ${SMS_ENABLED:true}
  account_sid: ${SMS_ACCOUNT_SID}
  auth_token: ${SMS_AUTH_TOKEN}
  from: ${SMS_FROM}
