server:
  port: ${PORT:8084}
spring:
  config:
    import: classpath:backend-defaults.yml
  application:
    name: ShopApprovalService
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/approvals}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
